dotenv: .env
wallets:
  goerli:
    privateKey: PUTGOERLITESTNETKEYHERE
compiler:
  solc:
    remappings:
      - "@uniswap=${SOLIDITY_ROOTDIR}/dependencies/Uniswap"
      - "@openzeppelin=${SOLIDITY_ROOTDIR}/dependencies/OpenZeppelin"
dependencies:
networks:
  default: mainnet-fork
  mainnet:
    host: https://mainnet.infura.io/v3/9165d99361774eb39d895e8623049a66
